-- Moody — Supabase schema (run this in Supabase → SQL Editor)
-- Safe with the public ANON key thanks to Row Level Security below.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) MEDICATIONS  (autocomplete + notice highlights)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.medications (
  id           bigint generated by default as identity primary key,
  name         text not null,
  molecule     text,
  form         text,
  highlights   jsonb,          -- { risques:[], effets:[], precautions:[], notice_url:"" }
  created_at   timestamptz default now()
);
-- prefix-friendly index for autocomplete (no extension needed)
create index if not exists medications_name_lower on public.medications (lower(name) text_pattern_ops);

alter table public.medications enable row level security;
drop policy if exists "meds readable by anyone" on public.medications;
create policy "meds readable by anyone" on public.medications for select using (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) SHARES  (single-use QR consult links)
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.shares (
  id            uuid primary key default gen_random_uuid(),
  token         text unique not null,
  created_at    timestamptz default now(),
  expires_at    timestamptz not null,
  used          boolean default false,
  doctor_name   text,
  guest_allowed boolean default true,
  payload       jsonb not null,   -- selected medical info + prescriptions metadata
  pdf_urls      text[] default '{}'
);

alter table public.shares enable row level security;
-- The patient's app (anon) may CREATE a share…
drop policy if exists "anyone can create a share" on public.shares;
create policy "anyone can create a share" on public.shares for insert with check (true);
-- …but NOT read it directly. Reading happens only via the single-use function below.

-- Atomic single-use read: returns the share once, then marks it used.
create or replace function public.consume_share(p_token text)
returns table (doctor_name text, guest_allowed boolean, payload jsonb, pdf_urls text[])
language plpgsql
security definer
set search_path = public
as $$
declare r public.shares%rowtype;
begin
  select * into r from public.shares where token = p_token for update;
  if not found then raise exception 'not_found'; end if;
  if r.used then raise exception 'already_used'; end if;
  if r.expires_at < now() then raise exception 'expired'; end if;
  update public.shares set used = true where id = r.id;
  return query select r.doctor_name, r.guest_allowed, r.payload, r.pdf_urls;
end;
$$;
grant execute on function public.consume_share(text) to anon;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) STORAGE bucket for attached PDFs (public bucket, unguessable random paths)
-- ─────────────────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public) values ('shares', 'shares', true)
  on conflict (id) do nothing;
drop policy if exists "anyone can upload a share pdf" on storage.objects;
create policy "anyone can upload a share pdf" on storage.objects for insert
  to anon with check (bucket_id = 'shares');
drop policy if exists "share pdfs are public" on storage.objects;
create policy "share pdfs are public" on storage.objects for select
  using (bucket_id = 'shares');

-- Optional cleanup helper (run manually or via a scheduled job) to purge old shares:
-- delete from public.shares where expires_at < now() - interval '7 days';

-- ─────────────────────────────────────────────────────────────────────────────
-- 4) BACKUPS  (encrypted personal cloud backup — the restore code IS the key)
-- ─────────────────────────────────────────────────────────────────────────────
-- The whole payload is AES-GCM encrypted on the device with a key derived from a
-- secret restore code. The row id is sha256(code), so the server never sees the
-- code and stores only ciphertext it cannot read.
create table if not exists public.backups (
  id          text primary key,
  iv          text not null,
  cipher      text not null,
  updated_at  timestamptz default now()
);
alter table public.backups enable row level security;
drop policy if exists "backup insert" on public.backups;
create policy "backup insert" on public.backups for insert to anon with check (true);
drop policy if exists "backup update" on public.backups;
create policy "backup update" on public.backups for update to anon using (true) with check (true);
drop policy if exists "backup read" on public.backups;
create policy "backup read" on public.backups for select to anon using (true);
