# -*- coding: utf-8 -*-
"""Corpus d'entraînement/test : (phrase, intent attendu). Réaliste : argot, fautes, tournures orales."""
CORPUS = [
    # crises — suicide (ne JAMAIS rater)
    ("j'ai envie de mourir", "crisis_suicide"),
    ("je veux en finir avec tout ça", "crisis_suicide"),
    ("franchement à quoi bon continuer", "crisis_suicide"),
    ("je suis un fardeau pour tout le monde", "crisis_suicide"),
    ("vous seriez mieux sans moi", "crisis_suicide"),
    ("j'ai plus envie de vivre du tout", "crisis_suicide"),
    ("jen peux plus de cette vie", "crisis_suicide"),
    ("je pense à me faire du mal", "crisis_suicide"),
    ("marre de vivre comme ça", "crisis_suicide"),
    ("je veux mettre fin à mes jours", "crisis_suicide"),
    # crises — panique
    ("je fais une crise d'angoisse là", "crisis_panic"),
    ("je crois que je fais une crise de panique", "crisis_panic"),
    ("mon coeur s'emballe je panique", "crisis_panic"),
    ("je tremble et j'étouffe aidez moi", "crisis_panic"),
    ("j'ai une attaque de panique", "crisis_panic"),
    ("je perds le controle je flippe grave", "crisis_panic"),
    # crises — violence
    ("mon copain me frappe", "crisis_violence"),
    ("il me menace tous les soirs", "crisis_violence"),
    ("j'ai peur de rentrer chez moi ce soir", "crisis_violence"),
    ("mon mari est violent avec moi", "crisis_violence"),
    # crises — médicales
    ("j'ai une douleur dans la poitrine qui irradie", "crisis_medical"),
    ("mon pere a le visage paralysé d'un coup", "crisis_medical"),
    ("je n'arrive plus à respirer", "crisis_medical"),
    ("ma mère a perdu connaissance", "crisis_medical"),
    # émotions
    ("je suis trop triste ce soir", "emo_sad"),
    ("gros coup de blues aujourd'hui", "emo_sad"),
    ("jai le cafard", "emo_sad"),
    ("le moral est à zéro", "emo_sad"),
    ("j'ai juste envie de pleurer", "emo_sad"),
    ("ca va pas fort en ce moment", "emo_sad"),
    ("je broie du noir depuis ce matin", "emo_sad"),
    ("j'ai trop le seum", "emo_sad"),
    ("je suis hyper stressée pour demain", "emo_anxious"),
    ("j'ai une boule au ventre", "emo_anxious"),
    ("je cogite trop je n'arrive pas à m'arrêter", "emo_anxious"),
    ("je flippe pour mon rendez vous", "emo_anxious"),
    ("je suis anxieuse toute la journée", "emo_anxious"),
    ("chuis tendu comme un arc", "emo_anxious"),
    ("je suis vénère aujourd'hui ça m'énerve tout", "emo_angry"),
    ("j'ai envie de tout casser", "emo_angry"),
    ("je suis hors de moi", "emo_angry"),
    ("ça me saoule tout ça", "emo_angry"),
    ("je me sens tellement seule", "emo_lonely"),
    ("personne ne me comprend", "emo_lonely"),
    ("j'ai personne à qui parler", "emo_lonely"),
    ("je me sens isolée de tout le monde", "emo_lonely"),
    ("je suis épuisée je n'en peux plus", "emo_tired"),
    ("chuis crevée", "emo_tired"),
    ("je suis au bout du rouleau", "emo_tired"),
    ("je sature complètement", "emo_tired"),
    ("je crois que je fais un burn out", "emo_tired"),
    ("je m'en veux tellement", "emo_guilt"),
    ("tout est de ma faute", "emo_guilt"),
    ("je suis nulle je rate tout", "emo_guilt"),
    ("j'ai honte de moi", "emo_guilt"),
    ("je me déteste", "emo_guilt"),
    ("je suis trop contente aujourd'hui", "emo_joy"),
    ("super journée je pète la forme", "emo_joy"),
    ("je suis fière de moi", "emo_joy"),
    ("ça va super bien en ce moment", "emo_joy"),
    ("il m'a quittée hier soir", "emo_heartbreak"),
    ("je vis une rupture difficile", "emo_heartbreak"),
    ("j'ai le coeur brisé", "emo_heartbreak"),
    ("je pense encore à mon ex", "emo_heartbreak"),
    ("ma grand-mère est décédée la semaine dernière", "emo_grief"),
    ("je traverse un deuil", "emo_grief"),
    ("j'ai perdu ma mère il y a un mois", "emo_grief"),
    # actions
    ("j'ai bu 3 verres d'eau", "act_water"),
    ("note 2 verres d'eau stp", "act_water"),
    ("ajoute de l'eau j'en ai bu un grand verre", "act_water"),
    ("j'ai fumé une clope", "act_conso"),
    ("j'ai pris un café", "act_conso"),
    ("note un monster", "act_conso"),
    ("j'ai bu une bière ce midi", "act_conso"),
    ("j'ai pris ma douche", "act_hygiene"),
    ("je me suis brossé les dents", "act_hygiene"),
    ("douche prise ce matin", "act_hygiene"),
    ("note mon humeur à 7", "act_mood_log"),
    ("enregistre mon humeur 8 sur 10", "act_mood_log"),
    ("j'ai pris mes médicaments ce matin", "act_med_taken"),
    ("médicament pris", "act_med_taken"),
    ("j'ai pris mon cachet", "act_med_taken"),
    ("la sertraline me donne des nausées", "act_side_effect"),
    ("effet secondaire bizarre depuis que je prends mon traitement", "act_side_effect"),
    ("ouvre le rapport médecin", "act_open_report"),
    ("montre le rapport du mois", "act_open_report"),
    ("génère le rapport pour mon médecin", "act_open_report"),
    ("ouvre les réglages", "act_open_settings"),
    ("je veux ajouter un médicament", "act_open_settings"),
    ("changer mes rappels", "act_open_settings"),
    ("on fait mon bilan", "act_start_bilan"),
    ("bilan moody", "act_start_bilan"),
    ("je veux faire le point", "act_start_bilan"),
    ("je veux suivre un produit", "act_add_product"),
    ("suivre ma conso de café", "act_add_product"),
    # questions données
    ("quelle est ma moyenne d'humeur", "q_mood_avg"),
    ("comment évolue mon humeur ce mois-ci", "q_mood_avg"),
    ("mes stats d'humeur", "q_mood_avg"),
    ("combien j'ai dormi cette semaine", "q_sleep"),
    ("ma moyenne de sommeil", "q_sleep"),
    ("je dors combien en ce moment", "q_sleep"),
    ("liste de mes médocs", "q_meds"),
    ("c'est quoi mon traitement", "q_meds"),
    ("combien de cafés cette semaine", "q_conso_stats"),
    ("combien de cigarettes j'ai fumé", "q_conso_stats"),
    ("combien d'eau aujourd'hui", "q_water"),
    ("quelle météo aujourd'hui", "q_weather"),
    ("il va pleuvoir", "q_weather"),
    ("je dois prendre un parapluie", "q_weather"),
    ("on est quel jour", "q_date"),
    ("il est quelle heure", "q_date"),
    ("c'est quoi le doliprane", "q_drug"),
    ("à quoi sert le levothyrox", "q_drug"),
    ("effets du xanax", "q_drug"),
    ("posologie de l'ibuprofène", "q_drug"),
    ("quel spécialiste pour mes migraines", "q_specialist"),
    ("qui consulter pour mon dos", "q_specialist"),
    ("je dois voir quel médecin pour ma peau", "q_specialist"),
    ("donne moi un conseil pour dormir", "q_advice"),
    ("comment gérer mon stress", "q_advice"),
    ("motive moi", "q_advice"),
    ("une astuce pour aller mieux", "q_advice"),
    # social
    ("salut moody", "s_greeting"),
    ("coucou", "s_greeting"),
    ("bonsoir", "s_greeting"),
    ("merci beaucoup", "s_thanks"),
    ("t'es top merci", "s_thanks"),
    ("bonne nuit à demain", "s_bye"),
    ("je te laisse", "s_bye"),
    ("comment vas-tu", "s_how_are_you"),
    ("ça va toi", "s_how_are_you"),
    ("t'es qui en fait", "s_who"),
    ("tu peux faire quoi", "s_who"),
    ("que sais-tu faire", "s_who"),
]
